###################################################################

# Created by write_sdc on Tue Jun 2 20:38:15 2026

###################################################################
set sdc_version 2.0

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_operating_conditions -max slow -max_library NangateOpenCellLibrary_ss0p95v125c -min low_temp -min_library NangateOpenCellLibrary_ff1p25vn40c
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports icache_bus_if.req_ready]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports icache_bus_if.rsp_valid]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[31]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[30]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[29]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[28]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[27]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[26]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[25]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[24]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[23]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[22]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[21]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[20]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[19]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[18]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[17]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[16]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[15]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[14]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[13]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[12]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[11]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[10]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[9]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[8]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[7]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[6]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[5]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[4]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_data[0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_tag[2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_tag[1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {icache_bus_if.rsp_tag[0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports schedule_if.valid]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[uuid][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[wid][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[wid][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[tmask][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[tmask][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[tmask][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[tmask][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][29]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][28]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][27]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][26]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][25]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][24]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][23]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][22]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][21]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][20]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][19]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][18]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][17]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][16]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][15]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][14]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][13]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][12]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][11]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][10]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][9]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][8]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][7]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][6]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][5]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][4]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {schedule_if.data[PC][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports fetch_if.ready]
set_load -pin_load 0.5 [get_ports icache_bus_if.req_valid]
set_load -pin_load 0.5 [get_ports icache_bus_if.req_rw]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[29]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[28]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[27]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[26]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[25]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[24]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[23]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[22]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[21]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[20]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[19]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[18]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[17]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[16]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[15]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[14]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[13]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[12]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[11]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[10]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[9]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[8]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[7]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[6]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[5]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[4]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[3]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[2]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[1]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_addr[0]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[31]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[30]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[29]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[28]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[27]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[26]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[25]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[24]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[23]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[22]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[21]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[20]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[19]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[18]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[17]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[16]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[15]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[14]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[13]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[12]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[11]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[10]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[9]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[8]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[7]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[6]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[5]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[4]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[3]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[2]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[1]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_data[0]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_byteen[3]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_byteen[2]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_byteen[1]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_byteen[0]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_flags[2]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_flags[1]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_flags[0]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_tag[2]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_tag[1]}]
set_load -pin_load 0.5 [get_ports {icache_bus_if.req_tag[0]}]
set_load -pin_load 0.5 [get_ports icache_bus_if.rsp_ready]
set_load -pin_load 0.5 [get_ports schedule_if.ready]
set_load -pin_load 0.5 [get_ports fetch_if.valid]
set_load -pin_load 0.5 [get_ports {fetch_if.data[uuid][0]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[wid][1]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[wid][0]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[tmask][3]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[tmask][2]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[tmask][1]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[tmask][0]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][29]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][28]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][27]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][26]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][25]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][24]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][23]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][22]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][21]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][20]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][19]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][18]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][17]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][16]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][15]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][14]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][13]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][12]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][11]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][10]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][9]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][8]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][7]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][6]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][5]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][4]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][3]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][2]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][1]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[PC][0]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][31]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][30]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][29]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][28]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][27]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][26]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][25]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][24]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][23]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][22]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][21]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][20]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][19]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][18]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][17]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][16]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][15]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][14]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][13]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][12]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][11]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][10]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][9]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][8]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][7]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][6]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][5]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][4]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][3]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][2]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][1]}]
set_load -pin_load 0.5 [get_ports {fetch_if.data[instr][0]}]
create_clock [get_ports clk]  -name CLK  -period 4  -waveform {0 2}
set_clock_latency 0  [get_clocks CLK]
set_clock_uncertainty -setup 0.25  [get_clocks CLK]
set_clock_uncertainty -hold 0.05  [get_clocks CLK]
set_clock_transition -max -rise 0.1 [get_clocks CLK]
set_clock_transition -min -rise 0.1 [get_clocks CLK]
set_clock_transition -max -fall 0.1 [get_clocks CLK]
set_clock_transition -min -fall 0.1 [get_clocks CLK]
group_path -name INOUT  -from [list [get_ports clk] [get_ports reset] [get_ports icache_bus_if.req_ready] [get_ports icache_bus_if.rsp_valid] [get_ports {icache_bus_if.rsp_data[31]}] [get_ports {icache_bus_if.rsp_data[30]}] [get_ports {icache_bus_if.rsp_data[29]}] [get_ports {icache_bus_if.rsp_data[28]}] [get_ports {icache_bus_if.rsp_data[27]}] [get_ports {icache_bus_if.rsp_data[26]}] [get_ports {icache_bus_if.rsp_data[25]}] [get_ports {icache_bus_if.rsp_data[24]}] [get_ports {icache_bus_if.rsp_data[23]}] [get_ports {icache_bus_if.rsp_data[22]}] [get_ports {icache_bus_if.rsp_data[21]}] [get_ports {icache_bus_if.rsp_data[20]}] [get_ports {icache_bus_if.rsp_data[19]}] [get_ports {icache_bus_if.rsp_data[18]}] [get_ports {icache_bus_if.rsp_data[17]}] [get_ports {icache_bus_if.rsp_data[16]}] [get_ports {icache_bus_if.rsp_data[15]}] [get_ports {icache_bus_if.rsp_data[14]}] [get_ports {icache_bus_if.rsp_data[13]}] [get_ports {icache_bus_if.rsp_data[12]}] [get_ports {icache_bus_if.rsp_data[11]}] [get_ports {icache_bus_if.rsp_data[10]}] [get_ports {icache_bus_if.rsp_data[9]}] [get_ports {icache_bus_if.rsp_data[8]}] [get_ports {icache_bus_if.rsp_data[7]}] [get_ports {icache_bus_if.rsp_data[6]}] [get_ports {icache_bus_if.rsp_data[5]}] [get_ports {icache_bus_if.rsp_data[4]}] [get_ports {icache_bus_if.rsp_data[3]}] [get_ports {icache_bus_if.rsp_data[2]}] [get_ports {icache_bus_if.rsp_data[1]}] [get_ports {icache_bus_if.rsp_data[0]}] [get_ports {icache_bus_if.rsp_tag[2]}] [get_ports {icache_bus_if.rsp_tag[1]}] [get_ports {icache_bus_if.rsp_tag[0]}] [get_ports schedule_if.valid] [get_ports {schedule_if.data[uuid][0]}] [get_ports {schedule_if.data[wid][1]}] [get_ports {schedule_if.data[wid][0]}] [get_ports {schedule_if.data[tmask][3]}] [get_ports {schedule_if.data[tmask][2]}] [get_ports {schedule_if.data[tmask][1]}] [get_ports {schedule_if.data[tmask][0]}] [get_ports {schedule_if.data[PC][29]}] [get_ports {schedule_if.data[PC][28]}] [get_ports {schedule_if.data[PC][27]}] [get_ports {schedule_if.data[PC][26]}] [get_ports {schedule_if.data[PC][25]}] [get_ports {schedule_if.data[PC][24]}] [get_ports {schedule_if.data[PC][23]}] [get_ports {schedule_if.data[PC][22]}] [get_ports {schedule_if.data[PC][21]}] [get_ports {schedule_if.data[PC][20]}] [get_ports {schedule_if.data[PC][19]}] [get_ports {schedule_if.data[PC][18]}] [get_ports {schedule_if.data[PC][17]}] [get_ports {schedule_if.data[PC][16]}] [get_ports {schedule_if.data[PC][15]}] [get_ports {schedule_if.data[PC][14]}] [get_ports {schedule_if.data[PC][13]}] [get_ports {schedule_if.data[PC][12]}] [get_ports {schedule_if.data[PC][11]}] [get_ports {schedule_if.data[PC][10]}] [get_ports {schedule_if.data[PC][9]}] [get_ports {schedule_if.data[PC][8]}] [get_ports {schedule_if.data[PC][7]}] [get_ports {schedule_if.data[PC][6]}] [get_ports {schedule_if.data[PC][5]}] [get_ports {schedule_if.data[PC][4]}] [get_ports {schedule_if.data[PC][3]}] [get_ports {schedule_if.data[PC][2]}] [get_ports {schedule_if.data[PC][1]}] [get_ports {schedule_if.data[PC][0]}] [get_ports fetch_if.ready]]  -to [list [get_ports icache_bus_if.req_valid] [get_ports icache_bus_if.req_rw] [get_ports {icache_bus_if.req_addr[29]}] [get_ports {icache_bus_if.req_addr[28]}] [get_ports {icache_bus_if.req_addr[27]}] [get_ports {icache_bus_if.req_addr[26]}] [get_ports {icache_bus_if.req_addr[25]}] [get_ports {icache_bus_if.req_addr[24]}] [get_ports {icache_bus_if.req_addr[23]}] [get_ports {icache_bus_if.req_addr[22]}] [get_ports {icache_bus_if.req_addr[21]}] [get_ports {icache_bus_if.req_addr[20]}] [get_ports {icache_bus_if.req_addr[19]}] [get_ports {icache_bus_if.req_addr[18]}] [get_ports {icache_bus_if.req_addr[17]}] [get_ports {icache_bus_if.req_addr[16]}] [get_ports {icache_bus_if.req_addr[15]}] [get_ports {icache_bus_if.req_addr[14]}] [get_ports {icache_bus_if.req_addr[13]}] [get_ports {icache_bus_if.req_addr[12]}] [get_ports {icache_bus_if.req_addr[11]}] [get_ports {icache_bus_if.req_addr[10]}] [get_ports {icache_bus_if.req_addr[9]}] [get_ports {icache_bus_if.req_addr[8]}] [get_ports {icache_bus_if.req_addr[7]}] [get_ports {icache_bus_if.req_addr[6]}] [get_ports {icache_bus_if.req_addr[5]}] [get_ports {icache_bus_if.req_addr[4]}] [get_ports {icache_bus_if.req_addr[3]}] [get_ports {icache_bus_if.req_addr[2]}] [get_ports {icache_bus_if.req_addr[1]}] [get_ports {icache_bus_if.req_addr[0]}] [get_ports {icache_bus_if.req_data[31]}] [get_ports {icache_bus_if.req_data[30]}] [get_ports {icache_bus_if.req_data[29]}] [get_ports {icache_bus_if.req_data[28]}] [get_ports {icache_bus_if.req_data[27]}] [get_ports {icache_bus_if.req_data[26]}] [get_ports {icache_bus_if.req_data[25]}] [get_ports {icache_bus_if.req_data[24]}] [get_ports {icache_bus_if.req_data[23]}] [get_ports {icache_bus_if.req_data[22]}] [get_ports {icache_bus_if.req_data[21]}] [get_ports {icache_bus_if.req_data[20]}] [get_ports {icache_bus_if.req_data[19]}] [get_ports {icache_bus_if.req_data[18]}] [get_ports {icache_bus_if.req_data[17]}] [get_ports {icache_bus_if.req_data[16]}] [get_ports {icache_bus_if.req_data[15]}] [get_ports {icache_bus_if.req_data[14]}] [get_ports {icache_bus_if.req_data[13]}] [get_ports {icache_bus_if.req_data[12]}] [get_ports {icache_bus_if.req_data[11]}] [get_ports {icache_bus_if.req_data[10]}] [get_ports {icache_bus_if.req_data[9]}] [get_ports {icache_bus_if.req_data[8]}] [get_ports {icache_bus_if.req_data[7]}] [get_ports {icache_bus_if.req_data[6]}] [get_ports {icache_bus_if.req_data[5]}] [get_ports {icache_bus_if.req_data[4]}] [get_ports {icache_bus_if.req_data[3]}] [get_ports {icache_bus_if.req_data[2]}] [get_ports {icache_bus_if.req_data[1]}] [get_ports {icache_bus_if.req_data[0]}] [get_ports {icache_bus_if.req_byteen[3]}] [get_ports {icache_bus_if.req_byteen[2]}] [get_ports {icache_bus_if.req_byteen[1]}] [get_ports {icache_bus_if.req_byteen[0]}] [get_ports {icache_bus_if.req_flags[2]}] [get_ports {icache_bus_if.req_flags[1]}] [get_ports {icache_bus_if.req_flags[0]}] [get_ports {icache_bus_if.req_tag[2]}] [get_ports {icache_bus_if.req_tag[1]}] [get_ports {icache_bus_if.req_tag[0]}] [get_ports icache_bus_if.rsp_ready] [get_ports schedule_if.ready] [get_ports fetch_if.valid] [get_ports {fetch_if.data[uuid][0]}] [get_ports {fetch_if.data[wid][1]}] [get_ports {fetch_if.data[wid][0]}] [get_ports {fetch_if.data[tmask][3]}] [get_ports {fetch_if.data[tmask][2]}] [get_ports {fetch_if.data[tmask][1]}] [get_ports {fetch_if.data[tmask][0]}] [get_ports {fetch_if.data[PC][29]}] [get_ports {fetch_if.data[PC][28]}] [get_ports {fetch_if.data[PC][27]}] [get_ports {fetch_if.data[PC][26]}] [get_ports {fetch_if.data[PC][25]}] [get_ports {fetch_if.data[PC][24]}] [get_ports {fetch_if.data[PC][23]}] [get_ports {fetch_if.data[PC][22]}] [get_ports {fetch_if.data[PC][21]}] [get_ports {fetch_if.data[PC][20]}] [get_ports {fetch_if.data[PC][19]}] [get_ports {fetch_if.data[PC][18]}] [get_ports {fetch_if.data[PC][17]}] [get_ports {fetch_if.data[PC][16]}] [get_ports {fetch_if.data[PC][15]}] [get_ports {fetch_if.data[PC][14]}] [get_ports {fetch_if.data[PC][13]}] [get_ports {fetch_if.data[PC][12]}] [get_ports {fetch_if.data[PC][11]}] [get_ports {fetch_if.data[PC][10]}] [get_ports {fetch_if.data[PC][9]}] [get_ports {fetch_if.data[PC][8]}] [get_ports {fetch_if.data[PC][7]}] [get_ports {fetch_if.data[PC][6]}] [get_ports {fetch_if.data[PC][5]}] [get_ports {fetch_if.data[PC][4]}] [get_ports {fetch_if.data[PC][3]}] [get_ports {fetch_if.data[PC][2]}] [get_ports {fetch_if.data[PC][1]}] [get_ports {fetch_if.data[PC][0]}] [get_ports {fetch_if.data[instr][31]}] [get_ports {fetch_if.data[instr][30]}] [get_ports {fetch_if.data[instr][29]}] [get_ports {fetch_if.data[instr][28]}] [get_ports {fetch_if.data[instr][27]}] [get_ports {fetch_if.data[instr][26]}] [get_ports {fetch_if.data[instr][25]}] [get_ports {fetch_if.data[instr][24]}] [get_ports {fetch_if.data[instr][23]}] [get_ports {fetch_if.data[instr][22]}] [get_ports {fetch_if.data[instr][21]}] [get_ports {fetch_if.data[instr][20]}] [get_ports {fetch_if.data[instr][19]}] [get_ports {fetch_if.data[instr][18]}] [get_ports {fetch_if.data[instr][17]}] [get_ports {fetch_if.data[instr][16]}] [get_ports {fetch_if.data[instr][15]}] [get_ports {fetch_if.data[instr][14]}] [get_ports {fetch_if.data[instr][13]}] [get_ports {fetch_if.data[instr][12]}] [get_ports {fetch_if.data[instr][11]}] [get_ports {fetch_if.data[instr][10]}] [get_ports {fetch_if.data[instr][9]}] [get_ports {fetch_if.data[instr][8]}] [get_ports {fetch_if.data[instr][7]}] [get_ports {fetch_if.data[instr][6]}] [get_ports {fetch_if.data[instr][5]}] [get_ports {fetch_if.data[instr][4]}] [get_ports {fetch_if.data[instr][3]}] [get_ports {fetch_if.data[instr][2]}] [get_ports {fetch_if.data[instr][1]}] [get_ports {fetch_if.data[instr][0]}]]
group_path -name INREG  -from [list [get_ports clk] [get_ports reset] [get_ports icache_bus_if.req_ready] [get_ports icache_bus_if.rsp_valid] [get_ports {icache_bus_if.rsp_data[31]}] [get_ports {icache_bus_if.rsp_data[30]}] [get_ports {icache_bus_if.rsp_data[29]}] [get_ports {icache_bus_if.rsp_data[28]}] [get_ports {icache_bus_if.rsp_data[27]}] [get_ports {icache_bus_if.rsp_data[26]}] [get_ports {icache_bus_if.rsp_data[25]}] [get_ports {icache_bus_if.rsp_data[24]}] [get_ports {icache_bus_if.rsp_data[23]}] [get_ports {icache_bus_if.rsp_data[22]}] [get_ports {icache_bus_if.rsp_data[21]}] [get_ports {icache_bus_if.rsp_data[20]}] [get_ports {icache_bus_if.rsp_data[19]}] [get_ports {icache_bus_if.rsp_data[18]}] [get_ports {icache_bus_if.rsp_data[17]}] [get_ports {icache_bus_if.rsp_data[16]}] [get_ports {icache_bus_if.rsp_data[15]}] [get_ports {icache_bus_if.rsp_data[14]}] [get_ports {icache_bus_if.rsp_data[13]}] [get_ports {icache_bus_if.rsp_data[12]}] [get_ports {icache_bus_if.rsp_data[11]}] [get_ports {icache_bus_if.rsp_data[10]}] [get_ports {icache_bus_if.rsp_data[9]}] [get_ports {icache_bus_if.rsp_data[8]}] [get_ports {icache_bus_if.rsp_data[7]}] [get_ports {icache_bus_if.rsp_data[6]}] [get_ports {icache_bus_if.rsp_data[5]}] [get_ports {icache_bus_if.rsp_data[4]}] [get_ports {icache_bus_if.rsp_data[3]}] [get_ports {icache_bus_if.rsp_data[2]}] [get_ports {icache_bus_if.rsp_data[1]}] [get_ports {icache_bus_if.rsp_data[0]}] [get_ports {icache_bus_if.rsp_tag[2]}] [get_ports {icache_bus_if.rsp_tag[1]}] [get_ports {icache_bus_if.rsp_tag[0]}] [get_ports schedule_if.valid] [get_ports {schedule_if.data[uuid][0]}] [get_ports {schedule_if.data[wid][1]}] [get_ports {schedule_if.data[wid][0]}] [get_ports {schedule_if.data[tmask][3]}] [get_ports {schedule_if.data[tmask][2]}] [get_ports {schedule_if.data[tmask][1]}] [get_ports {schedule_if.data[tmask][0]}] [get_ports {schedule_if.data[PC][29]}] [get_ports {schedule_if.data[PC][28]}] [get_ports {schedule_if.data[PC][27]}] [get_ports {schedule_if.data[PC][26]}] [get_ports {schedule_if.data[PC][25]}] [get_ports {schedule_if.data[PC][24]}] [get_ports {schedule_if.data[PC][23]}] [get_ports {schedule_if.data[PC][22]}] [get_ports {schedule_if.data[PC][21]}] [get_ports {schedule_if.data[PC][20]}] [get_ports {schedule_if.data[PC][19]}] [get_ports {schedule_if.data[PC][18]}] [get_ports {schedule_if.data[PC][17]}] [get_ports {schedule_if.data[PC][16]}] [get_ports {schedule_if.data[PC][15]}] [get_ports {schedule_if.data[PC][14]}] [get_ports {schedule_if.data[PC][13]}] [get_ports {schedule_if.data[PC][12]}] [get_ports {schedule_if.data[PC][11]}] [get_ports {schedule_if.data[PC][10]}] [get_ports {schedule_if.data[PC][9]}] [get_ports {schedule_if.data[PC][8]}] [get_ports {schedule_if.data[PC][7]}] [get_ports {schedule_if.data[PC][6]}] [get_ports {schedule_if.data[PC][5]}] [get_ports {schedule_if.data[PC][4]}] [get_ports {schedule_if.data[PC][3]}] [get_ports {schedule_if.data[PC][2]}] [get_ports {schedule_if.data[PC][1]}] [get_ports {schedule_if.data[PC][0]}] [get_ports fetch_if.ready]]
group_path -name REGOUT  -to [list [get_ports icache_bus_if.req_valid] [get_ports icache_bus_if.req_rw] [get_ports {icache_bus_if.req_addr[29]}] [get_ports {icache_bus_if.req_addr[28]}] [get_ports {icache_bus_if.req_addr[27]}] [get_ports {icache_bus_if.req_addr[26]}] [get_ports {icache_bus_if.req_addr[25]}] [get_ports {icache_bus_if.req_addr[24]}] [get_ports {icache_bus_if.req_addr[23]}] [get_ports {icache_bus_if.req_addr[22]}] [get_ports {icache_bus_if.req_addr[21]}] [get_ports {icache_bus_if.req_addr[20]}] [get_ports {icache_bus_if.req_addr[19]}] [get_ports {icache_bus_if.req_addr[18]}] [get_ports {icache_bus_if.req_addr[17]}] [get_ports {icache_bus_if.req_addr[16]}] [get_ports {icache_bus_if.req_addr[15]}] [get_ports {icache_bus_if.req_addr[14]}] [get_ports {icache_bus_if.req_addr[13]}] [get_ports {icache_bus_if.req_addr[12]}] [get_ports {icache_bus_if.req_addr[11]}] [get_ports {icache_bus_if.req_addr[10]}] [get_ports {icache_bus_if.req_addr[9]}] [get_ports {icache_bus_if.req_addr[8]}] [get_ports {icache_bus_if.req_addr[7]}] [get_ports {icache_bus_if.req_addr[6]}] [get_ports {icache_bus_if.req_addr[5]}] [get_ports {icache_bus_if.req_addr[4]}] [get_ports {icache_bus_if.req_addr[3]}] [get_ports {icache_bus_if.req_addr[2]}] [get_ports {icache_bus_if.req_addr[1]}] [get_ports {icache_bus_if.req_addr[0]}] [get_ports {icache_bus_if.req_data[31]}] [get_ports {icache_bus_if.req_data[30]}] [get_ports {icache_bus_if.req_data[29]}] [get_ports {icache_bus_if.req_data[28]}] [get_ports {icache_bus_if.req_data[27]}] [get_ports {icache_bus_if.req_data[26]}] [get_ports {icache_bus_if.req_data[25]}] [get_ports {icache_bus_if.req_data[24]}] [get_ports {icache_bus_if.req_data[23]}] [get_ports {icache_bus_if.req_data[22]}] [get_ports {icache_bus_if.req_data[21]}] [get_ports {icache_bus_if.req_data[20]}] [get_ports {icache_bus_if.req_data[19]}] [get_ports {icache_bus_if.req_data[18]}] [get_ports {icache_bus_if.req_data[17]}] [get_ports {icache_bus_if.req_data[16]}] [get_ports {icache_bus_if.req_data[15]}] [get_ports {icache_bus_if.req_data[14]}] [get_ports {icache_bus_if.req_data[13]}] [get_ports {icache_bus_if.req_data[12]}] [get_ports {icache_bus_if.req_data[11]}] [get_ports {icache_bus_if.req_data[10]}] [get_ports {icache_bus_if.req_data[9]}] [get_ports {icache_bus_if.req_data[8]}] [get_ports {icache_bus_if.req_data[7]}] [get_ports {icache_bus_if.req_data[6]}] [get_ports {icache_bus_if.req_data[5]}] [get_ports {icache_bus_if.req_data[4]}] [get_ports {icache_bus_if.req_data[3]}] [get_ports {icache_bus_if.req_data[2]}] [get_ports {icache_bus_if.req_data[1]}] [get_ports {icache_bus_if.req_data[0]}] [get_ports {icache_bus_if.req_byteen[3]}] [get_ports {icache_bus_if.req_byteen[2]}] [get_ports {icache_bus_if.req_byteen[1]}] [get_ports {icache_bus_if.req_byteen[0]}] [get_ports {icache_bus_if.req_flags[2]}] [get_ports {icache_bus_if.req_flags[1]}] [get_ports {icache_bus_if.req_flags[0]}] [get_ports {icache_bus_if.req_tag[2]}] [get_ports {icache_bus_if.req_tag[1]}] [get_ports {icache_bus_if.req_tag[0]}] [get_ports icache_bus_if.rsp_ready] [get_ports schedule_if.ready] [get_ports fetch_if.valid] [get_ports {fetch_if.data[uuid][0]}] [get_ports {fetch_if.data[wid][1]}] [get_ports {fetch_if.data[wid][0]}] [get_ports {fetch_if.data[tmask][3]}] [get_ports {fetch_if.data[tmask][2]}] [get_ports {fetch_if.data[tmask][1]}] [get_ports {fetch_if.data[tmask][0]}] [get_ports {fetch_if.data[PC][29]}] [get_ports {fetch_if.data[PC][28]}] [get_ports {fetch_if.data[PC][27]}] [get_ports {fetch_if.data[PC][26]}] [get_ports {fetch_if.data[PC][25]}] [get_ports {fetch_if.data[PC][24]}] [get_ports {fetch_if.data[PC][23]}] [get_ports {fetch_if.data[PC][22]}] [get_ports {fetch_if.data[PC][21]}] [get_ports {fetch_if.data[PC][20]}] [get_ports {fetch_if.data[PC][19]}] [get_ports {fetch_if.data[PC][18]}] [get_ports {fetch_if.data[PC][17]}] [get_ports {fetch_if.data[PC][16]}] [get_ports {fetch_if.data[PC][15]}] [get_ports {fetch_if.data[PC][14]}] [get_ports {fetch_if.data[PC][13]}] [get_ports {fetch_if.data[PC][12]}] [get_ports {fetch_if.data[PC][11]}] [get_ports {fetch_if.data[PC][10]}] [get_ports {fetch_if.data[PC][9]}] [get_ports {fetch_if.data[PC][8]}] [get_ports {fetch_if.data[PC][7]}] [get_ports {fetch_if.data[PC][6]}] [get_ports {fetch_if.data[PC][5]}] [get_ports {fetch_if.data[PC][4]}] [get_ports {fetch_if.data[PC][3]}] [get_ports {fetch_if.data[PC][2]}] [get_ports {fetch_if.data[PC][1]}] [get_ports {fetch_if.data[PC][0]}] [get_ports {fetch_if.data[instr][31]}] [get_ports {fetch_if.data[instr][30]}] [get_ports {fetch_if.data[instr][29]}] [get_ports {fetch_if.data[instr][28]}] [get_ports {fetch_if.data[instr][27]}] [get_ports {fetch_if.data[instr][26]}] [get_ports {fetch_if.data[instr][25]}] [get_ports {fetch_if.data[instr][24]}] [get_ports {fetch_if.data[instr][23]}] [get_ports {fetch_if.data[instr][22]}] [get_ports {fetch_if.data[instr][21]}] [get_ports {fetch_if.data[instr][20]}] [get_ports {fetch_if.data[instr][19]}] [get_ports {fetch_if.data[instr][18]}] [get_ports {fetch_if.data[instr][17]}] [get_ports {fetch_if.data[instr][16]}] [get_ports {fetch_if.data[instr][15]}] [get_ports {fetch_if.data[instr][14]}] [get_ports {fetch_if.data[instr][13]}] [get_ports {fetch_if.data[instr][12]}] [get_ports {fetch_if.data[instr][11]}] [get_ports {fetch_if.data[instr][10]}] [get_ports {fetch_if.data[instr][9]}] [get_ports {fetch_if.data[instr][8]}] [get_ports {fetch_if.data[instr][7]}] [get_ports {fetch_if.data[instr][6]}] [get_ports {fetch_if.data[instr][5]}] [get_ports {fetch_if.data[instr][4]}] [get_ports {fetch_if.data[instr][3]}] [get_ports {fetch_if.data[instr][2]}] [get_ports {fetch_if.data[instr][1]}] [get_ports {fetch_if.data[instr][0]}]]
set_input_delay -clock CLK  1.2  [get_ports icache_bus_if.req_ready]
set_input_delay -clock CLK  1.2  [get_ports icache_bus_if.rsp_valid]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[31]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[30]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[29]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[28]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[27]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[26]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[25]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[24]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[23]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[22]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[21]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[20]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[19]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[18]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[17]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[16]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[15]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[14]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[13]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[12]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[11]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[10]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[9]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[8]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[7]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[6]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[5]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[4]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[3]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[2]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[1]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_data[0]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_tag[2]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_tag[1]}]
set_input_delay -clock CLK  1.2  [get_ports {icache_bus_if.rsp_tag[0]}]
set_input_delay -clock CLK  1.2  [get_ports schedule_if.valid]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[uuid][0]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[wid][1]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[wid][0]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[tmask][3]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[tmask][2]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[tmask][1]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[tmask][0]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][29]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][28]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][27]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][26]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][25]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][24]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][23]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][22]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][21]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][20]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][19]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][18]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][17]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][16]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][15]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][14]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][13]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][12]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][11]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][10]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][9]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][8]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][7]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][6]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][5]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][4]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][3]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][2]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][1]}]
set_input_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][0]}]
set_input_delay -clock CLK  1.2  [get_ports fetch_if.ready]
set_output_delay -clock CLK  1.2  [get_ports icache_bus_if.req_valid]
set_output_delay -clock CLK  1.2  [get_ports icache_bus_if.req_rw]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[29]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[28]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[27]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[26]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[25]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[24]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[23]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[22]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[21]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[20]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[19]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[18]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[17]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[16]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[15]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[14]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[13]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[12]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[11]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[10]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[9]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[8]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[7]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[6]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[5]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[4]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[3]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[2]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[1]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_addr[0]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[31]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[30]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[29]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[28]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[27]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[26]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[25]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[24]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[23]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[22]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[21]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[20]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[19]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[18]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[17]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[16]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[15]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[14]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[13]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[12]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[11]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[10]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[9]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[8]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[7]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[6]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[5]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[4]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[3]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[2]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[1]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_data[0]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_byteen[3]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_byteen[2]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_byteen[1]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_byteen[0]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_flags[2]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_flags[1]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_flags[0]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_tag[2]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_tag[1]}]
set_output_delay -clock CLK  1.2  [get_ports {icache_bus_if.req_tag[0]}]
set_output_delay -clock CLK  1.2  [get_ports icache_bus_if.rsp_ready]
set_output_delay -clock CLK  1.2  [get_ports schedule_if.ready]
set_output_delay -clock CLK  1.2  [get_ports fetch_if.valid]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[uuid][0]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[wid][1]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[wid][0]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[tmask][3]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[tmask][2]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[tmask][1]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[tmask][0]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][29]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][28]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][27]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][26]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][25]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][24]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][23]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][22]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][21]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][20]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][19]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][18]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][17]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][16]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][15]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][14]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][13]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][12]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][11]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][10]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][9]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][8]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][7]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][6]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][5]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][4]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][3]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][2]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][1]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[PC][0]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][31]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][30]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][29]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][28]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][27]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][26]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][25]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][24]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][23]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][22]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][21]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][20]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][19]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][18]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][17]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][16]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][15]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][14]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][13]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][12]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][11]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][10]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][9]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][8]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][7]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][6]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][5]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][4]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][3]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][2]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][1]}]
set_output_delay -clock CLK  1.2  [get_ports {fetch_if.data[instr][0]}]
