###################################################################

# Created by write_sdc on Sun May 17 01:37:12 2026

###################################################################
set sdc_version 2.0

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_operating_conditions -max slow -max_library NangateOpenCellLibrary_ss0p95v125c -min low_temp -min_library NangateOpenCellLibrary_ff1p25vn40c
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports fetch_if.valid]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][43]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][42]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][41]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][40]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][39]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][38]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][37]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][36]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][35]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][34]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][33]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][32]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][31]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][30]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][29]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][28]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][27]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][26]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][25]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][24]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][23]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][22]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][21]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][20]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][19]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][18]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][17]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][16]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][15]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][14]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][13]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][12]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][11]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][10]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][9]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][8]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][7]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][6]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][5]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][4]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[uuid][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[wid][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[wid][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[tmask][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[tmask][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[tmask][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[tmask][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][31]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][30]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][29]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][28]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][27]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][26]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][25]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][24]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][23]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][22]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][21]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][20]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][19]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][18]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][17]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][16]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][15]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][14]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][13]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][12]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][11]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][10]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][9]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][8]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][7]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][6]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][5]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][4]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[PC][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][31]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][30]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][29]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][28]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][27]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][26]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][25]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][24]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][23]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][22]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][21]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][20]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][19]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][18]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][17]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][16]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][15]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][14]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][13]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][12]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][11]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][10]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][9]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][8]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][7]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][6]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][5]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][4]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {fetch_if.data[instr][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports decode_if.ready]
set_load -pin_load 0.5 [get_ports fetch_if.ready]
set_load -pin_load 0.5 [get_ports decode_if.valid]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][43]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][42]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][41]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][40]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][39]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][38]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][37]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][36]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][35]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][34]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][33]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][32]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][31]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][30]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][29]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][28]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][27]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][26]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][25]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][24]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][23]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][22]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][21]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][20]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][19]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][18]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][17]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][16]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][15]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][14]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][13]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][12]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][11]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][10]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][9]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][8]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][7]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][6]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][5]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][4]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][3]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][2]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][1]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[uuid][0]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[wid][1]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[wid][0]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[tmask][3]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[tmask][2]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[tmask][1]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[tmask][0]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][31]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][30]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][29]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][28]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][27]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][26]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][25]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][24]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][23]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][22]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][21]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][20]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][19]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][18]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][17]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][16]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][15]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][14]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][13]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][12]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][11]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][10]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][9]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][8]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][7]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][6]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][5]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][4]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][3]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][2]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][1]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[PC][0]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[ex_type][1]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[ex_type][0]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_type][3]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_type][2]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_type][1]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_type][0]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][36]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][35]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][34]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][33]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][32]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][31]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][30]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][29]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][28]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][27]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][26]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][25]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][24]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][23]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][22]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][21]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][20]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][19]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][18]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][17]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][16]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][15]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][14]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][13]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][12]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][11]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][10]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][9]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][8]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][7]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][6]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][5]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][4]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][3]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][2]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][1]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[op_args][0]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[wb]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[used_rs][2]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[used_rs][1]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[used_rs][0]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rd][5]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rd][4]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rd][3]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rd][2]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rd][1]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rd][0]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs1][5]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs1][4]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs1][3]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs1][2]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs1][1]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs1][0]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs2][5]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs2][4]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs2][3]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs2][2]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs2][1]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs2][0]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs3][5]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs3][4]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs3][3]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs3][2]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs3][1]}]
set_load -pin_load 0.5 [get_ports {decode_if.data[rs3][0]}]
set_load -pin_load 0.5 [get_ports decode_sched_if.valid]
set_load -pin_load 0.5 [get_ports decode_sched_if.unlock]
set_load -pin_load 0.5 [get_ports {decode_sched_if.wid[1]}]
set_load -pin_load 0.5 [get_ports {decode_sched_if.wid[0]}]
create_clock [get_ports clk]  -name CLK  -period 165  -waveform {0 82}
set_clock_latency 0  [get_clocks CLK]
set_clock_uncertainty -setup 0.25  [get_clocks CLK]
set_clock_uncertainty -hold 0.05  [get_clocks CLK]
set_clock_transition -max -rise 0.1 [get_clocks CLK]
set_clock_transition -min -rise 0.1 [get_clocks CLK]
set_clock_transition -max -fall 0.1 [get_clocks CLK]
set_clock_transition -min -fall 0.1 [get_clocks CLK]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][43]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][42]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][41]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][40]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][39]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][38]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][37]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][36]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][35]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][34]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][33]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][32]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][31]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][30]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][29]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][28]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][27]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][26]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][25]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][24]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][23]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][22]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][21]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][20]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][19]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][18]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][17]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][16]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][15]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][14]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][13]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][12]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][11]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][10]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][9]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][8]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][7]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][6]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][5]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][4]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][3]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][2]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][1]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[uuid][0]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[wid][1]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[wid][0]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[tmask][3]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[tmask][2]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[tmask][1]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[tmask][0]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][31]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][30]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][29]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][28]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][27]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][26]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][25]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][24]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][23]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][22]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][21]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][20]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][19]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][18]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][17]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][16]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][15]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][14]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][13]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][12]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][11]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][10]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][9]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][8]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][7]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][6]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][5]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][4]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][3]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][2]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][1]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[PC][0]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][31]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][30]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][29]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][28]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][27]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][26]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][25]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][24]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][23]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][22]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][21]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][20]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][19]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][18]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][17]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][16]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][15]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][14]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][13]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][12]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][11]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][10]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][9]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][8]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][7]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][6]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][5]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][4]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][3]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][2]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][1]}]
set_input_delay -clock CLK  49.5  [get_ports {fetch_if.data[instr][0]}]
set_input_delay -clock CLK  49.5  [get_ports fetch_if.valid]
set_input_delay -clock CLK  49.5  [get_ports decode_if.ready]
set_output_delay -clock CLK  49.5  [get_ports decode_if.valid]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][43]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][42]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][41]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][40]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][39]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][38]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][37]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][36]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][35]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][34]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][33]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][32]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][31]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][30]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][29]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][28]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][27]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][26]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][25]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][24]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][23]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][22]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][21]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][20]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][19]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][18]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][17]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][16]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][15]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][14]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][13]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][12]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][11]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][10]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][9]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][8]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][7]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][6]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][5]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][4]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][3]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][2]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[uuid][0]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[wid][1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[wid][0]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[tmask][3]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[tmask][2]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[tmask][1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[tmask][0]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][31]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][30]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][29]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][28]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][27]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][26]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][25]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][24]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][23]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][22]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][21]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][20]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][19]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][18]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][17]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][16]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][15]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][14]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][13]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][12]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][11]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][10]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][9]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][8]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][7]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][6]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][5]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][4]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][3]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][2]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[PC][0]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[ex_type][1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[ex_type][0]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_type][3]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_type][2]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_type][1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_type][0]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][36]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][35]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][34]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][33]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][32]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][31]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][30]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][29]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][28]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][27]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][26]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][25]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][24]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][23]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][22]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][21]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][20]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][19]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][18]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][17]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][16]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][15]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][14]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][13]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][12]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][11]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][10]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][9]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][8]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][7]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][6]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][5]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][4]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][3]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][2]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[op_args][0]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[wb]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[used_rs][2]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[used_rs][1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[used_rs][0]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rd][5]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rd][4]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rd][3]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rd][2]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rd][1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rd][0]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs1][5]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs1][4]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs1][3]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs1][2]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs1][1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs1][0]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs2][5]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs2][4]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs2][3]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs2][2]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs2][1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs2][0]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs3][5]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs3][4]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs3][3]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs3][2]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs3][1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_if.data[rs3][0]}]
set_output_delay -clock CLK  49.5  [get_ports decode_sched_if.valid]
set_output_delay -clock CLK  49.5  [get_ports decode_sched_if.unlock]
set_output_delay -clock CLK  49.5  [get_ports {decode_sched_if.wid[1]}]
set_output_delay -clock CLK  49.5  [get_ports {decode_sched_if.wid[0]}]
set_output_delay -clock CLK  49.5  [get_ports fetch_if.ready]
