###################################################################

# Created by write_sdc on Tue Jun 2 20:37:35 2026

###################################################################
set sdc_version 2.0

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_operating_conditions -max slow -max_library NangateOpenCellLibrary_ss0p95v125c -min low_temp -min_library NangateOpenCellLibrary_ff1p25vn40c
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][31]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][30]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][29]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][28]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][27]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][26]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][25]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][24]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][23]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][22]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][21]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][20]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][19]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][18]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][17]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][16]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][15]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][14]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][13]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][12]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][11]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][10]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][9]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][8]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][7]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][6]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][5]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][4]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_addr][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][31]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][30]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][29]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][28]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][27]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][26]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][25]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][24]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][23]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][22]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][21]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][20]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][19]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][18]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][17]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][16]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][15]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][14]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][13]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][12]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][11]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][10]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][9]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][8]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][7]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][6]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][5]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][4]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[startup_arg][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[mpm_class][7]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[mpm_class][6]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[mpm_class][5]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[mpm_class][4]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[mpm_class][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[mpm_class][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[mpm_class][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {base_dcrs[mpm_class][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports warp_ctl_if.valid]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wid[1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wid[0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[valid]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[wmask][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[wmask][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[wmask][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[wmask][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][29]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][28]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][27]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][26]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][25]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][24]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][23]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][22]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][21]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][20]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][19]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][18]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][17]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][16]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][15]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][14]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][13]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][12]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][11]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][10]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][9]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][8]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][7]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][6]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][5]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][4]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.wspawn[pc][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.tmc[valid]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.tmc[tmask][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.tmc[tmask][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.tmc[tmask][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.tmc[tmask][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[valid]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[is_dvg]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[then_tmask][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[then_tmask][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[then_tmask][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[then_tmask][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[else_tmask][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[else_tmask][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[else_tmask][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[else_tmask][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][29]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][28]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][27]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][26]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][25]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][24]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][23]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][22]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][21]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][20]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][19]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][18]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][17]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][16]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][15]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][14]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][13]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][12]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][11]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][10]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][9]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][8]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][7]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][6]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][5]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][4]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.split[next_pc][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.sjoin[valid]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.sjoin[stack_ptr][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.sjoin[stack_ptr][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.barrier[valid]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.barrier[id][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.barrier[is_global]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.barrier[size_m1][1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.barrier[size_m1][0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.barrier[is_noop]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.dvstack_wid[1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {warp_ctl_if.dvstack_wid[0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].valid}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].wid[1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].wid[0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].taken}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[29]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[28]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[27]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[26]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[25]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[24]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[23]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[22]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[21]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[20]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[19]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[18]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[17]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[16]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[15]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[14]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[13]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[12]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[11]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[10]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[9]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[8]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[7]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[6]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[5]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[4]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {branch_ctl_if[0].dest[0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports decode_sched_if.valid]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports decode_sched_if.unlock]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {decode_sched_if.wid[1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {decode_sched_if.wid[0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {issue_sched_if[0].valid}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {issue_sched_if[0].wis[1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {issue_sched_if[0].wis[0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {commit_sched_if.committed_warps[3]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {commit_sched_if.committed_warps[2]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {commit_sched_if.committed_warps[1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {commit_sched_if.committed_warps[0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports schedule_if.ready]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {sched_csr_if.alm_empty_wid[1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {sched_csr_if.alm_empty_wid[0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {sched_csr_if.unlock_wid[1]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports {sched_csr_if.unlock_wid[0]}]
set_driving_cell -lib_cell BUF_X2 -library NangateOpenCellLibrary_ss0p95v125c -pin Z [get_ports sched_csr_if.unlock_warp]
set_load -pin_load 0.5 [get_ports {warp_ctl_if.dvstack_ptr[1]}]
set_load -pin_load 0.5 [get_ports {warp_ctl_if.dvstack_ptr[0]}]
set_load -pin_load 0.5 [get_ports schedule_if.valid]
set_load -pin_load 0.5 [get_ports {schedule_if.data[uuid][0]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[wid][1]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[wid][0]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[tmask][3]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[tmask][2]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[tmask][1]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[tmask][0]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][29]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][28]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][27]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][26]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][25]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][24]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][23]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][22]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][21]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][20]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][19]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][18]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][17]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][16]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][15]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][14]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][13]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][12]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][11]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][10]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][9]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][8]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][7]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][6]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][5]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][4]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][3]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][2]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][1]}]
set_load -pin_load 0.5 [get_ports {schedule_if.data[PC][0]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[43]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[42]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[41]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[40]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[39]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[38]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[37]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[36]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[35]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[34]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[33]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[32]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[31]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[30]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[29]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[28]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[27]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[26]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[25]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[24]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[23]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[22]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[21]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[20]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[19]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[18]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[17]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[16]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[15]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[14]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[13]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[12]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[11]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[10]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[9]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[8]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[7]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[6]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[5]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[4]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[3]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[2]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[1]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.cycles[0]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.active_warps[3]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.active_warps[2]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.active_warps[1]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.active_warps[0]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[3][3]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[3][2]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[3][1]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[3][0]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[2][3]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[2][2]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[2][1]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[2][0]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[1][3]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[1][2]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[1][1]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[1][0]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[0][3]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[0][2]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[0][1]}]
set_load -pin_load 0.5 [get_ports {sched_csr_if.thread_masks[0][0]}]
set_load -pin_load 0.5 [get_ports sched_csr_if.alm_empty]
set_load -pin_load 0.5 [get_ports busy]
create_clock [get_ports clk]  -name CLK  -period 4  -waveform {0 2}
set_clock_latency 0  [get_clocks CLK]
set_clock_uncertainty -setup 0.25  [get_clocks CLK]
set_clock_uncertainty -hold 0.05  [get_clocks CLK]
set_clock_transition -max -rise 0.1 [get_clocks CLK]
set_clock_transition -min -rise 0.1 [get_clocks CLK]
set_clock_transition -max -fall 0.1 [get_clocks CLK]
set_clock_transition -min -fall 0.1 [get_clocks CLK]
group_path -name INOUT  -from [list [get_ports clk] [get_ports reset] [get_ports {base_dcrs[startup_addr][31]}] [get_ports {base_dcrs[startup_addr][30]}] [get_ports {base_dcrs[startup_addr][29]}] [get_ports {base_dcrs[startup_addr][28]}] [get_ports {base_dcrs[startup_addr][27]}] [get_ports {base_dcrs[startup_addr][26]}] [get_ports {base_dcrs[startup_addr][25]}] [get_ports {base_dcrs[startup_addr][24]}] [get_ports {base_dcrs[startup_addr][23]}] [get_ports {base_dcrs[startup_addr][22]}] [get_ports {base_dcrs[startup_addr][21]}] [get_ports {base_dcrs[startup_addr][20]}] [get_ports {base_dcrs[startup_addr][19]}] [get_ports {base_dcrs[startup_addr][18]}] [get_ports {base_dcrs[startup_addr][17]}] [get_ports {base_dcrs[startup_addr][16]}] [get_ports {base_dcrs[startup_addr][15]}] [get_ports {base_dcrs[startup_addr][14]}] [get_ports {base_dcrs[startup_addr][13]}] [get_ports {base_dcrs[startup_addr][12]}] [get_ports {base_dcrs[startup_addr][11]}] [get_ports {base_dcrs[startup_addr][10]}] [get_ports {base_dcrs[startup_addr][9]}] [get_ports {base_dcrs[startup_addr][8]}] [get_ports {base_dcrs[startup_addr][7]}] [get_ports {base_dcrs[startup_addr][6]}] [get_ports {base_dcrs[startup_addr][5]}] [get_ports {base_dcrs[startup_addr][4]}] [get_ports {base_dcrs[startup_addr][3]}] [get_ports {base_dcrs[startup_addr][2]}] [get_ports {base_dcrs[startup_addr][1]}] [get_ports {base_dcrs[startup_addr][0]}] [get_ports {base_dcrs[startup_arg][31]}] [get_ports {base_dcrs[startup_arg][30]}] [get_ports {base_dcrs[startup_arg][29]}] [get_ports {base_dcrs[startup_arg][28]}] [get_ports {base_dcrs[startup_arg][27]}] [get_ports {base_dcrs[startup_arg][26]}] [get_ports {base_dcrs[startup_arg][25]}] [get_ports {base_dcrs[startup_arg][24]}] [get_ports {base_dcrs[startup_arg][23]}] [get_ports {base_dcrs[startup_arg][22]}] [get_ports {base_dcrs[startup_arg][21]}] [get_ports {base_dcrs[startup_arg][20]}] [get_ports {base_dcrs[startup_arg][19]}] [get_ports {base_dcrs[startup_arg][18]}] [get_ports {base_dcrs[startup_arg][17]}] [get_ports {base_dcrs[startup_arg][16]}] [get_ports {base_dcrs[startup_arg][15]}] [get_ports {base_dcrs[startup_arg][14]}] [get_ports {base_dcrs[startup_arg][13]}] [get_ports {base_dcrs[startup_arg][12]}] [get_ports {base_dcrs[startup_arg][11]}] [get_ports {base_dcrs[startup_arg][10]}] [get_ports {base_dcrs[startup_arg][9]}] [get_ports {base_dcrs[startup_arg][8]}] [get_ports {base_dcrs[startup_arg][7]}] [get_ports {base_dcrs[startup_arg][6]}] [get_ports {base_dcrs[startup_arg][5]}] [get_ports {base_dcrs[startup_arg][4]}] [get_ports {base_dcrs[startup_arg][3]}] [get_ports {base_dcrs[startup_arg][2]}] [get_ports {base_dcrs[startup_arg][1]}] [get_ports {base_dcrs[startup_arg][0]}] [get_ports {base_dcrs[mpm_class][7]}] [get_ports {base_dcrs[mpm_class][6]}] [get_ports {base_dcrs[mpm_class][5]}] [get_ports {base_dcrs[mpm_class][4]}] [get_ports {base_dcrs[mpm_class][3]}] [get_ports {base_dcrs[mpm_class][2]}] [get_ports {base_dcrs[mpm_class][1]}] [get_ports {base_dcrs[mpm_class][0]}] [get_ports warp_ctl_if.valid] [get_ports {warp_ctl_if.wid[1]}] [get_ports {warp_ctl_if.wid[0]}] [get_ports {warp_ctl_if.wspawn[valid]}] [get_ports {warp_ctl_if.wspawn[wmask][3]}] [get_ports {warp_ctl_if.wspawn[wmask][2]}] [get_ports {warp_ctl_if.wspawn[wmask][1]}] [get_ports {warp_ctl_if.wspawn[wmask][0]}] [get_ports {warp_ctl_if.wspawn[pc][29]}] [get_ports {warp_ctl_if.wspawn[pc][28]}] [get_ports {warp_ctl_if.wspawn[pc][27]}] [get_ports {warp_ctl_if.wspawn[pc][26]}] [get_ports {warp_ctl_if.wspawn[pc][25]}] [get_ports {warp_ctl_if.wspawn[pc][24]}] [get_ports {warp_ctl_if.wspawn[pc][23]}] [get_ports {warp_ctl_if.wspawn[pc][22]}] [get_ports {warp_ctl_if.wspawn[pc][21]}] [get_ports {warp_ctl_if.wspawn[pc][20]}] [get_ports {warp_ctl_if.wspawn[pc][19]}] [get_ports {warp_ctl_if.wspawn[pc][18]}] [get_ports {warp_ctl_if.wspawn[pc][17]}] [get_ports {warp_ctl_if.wspawn[pc][16]}] [get_ports {warp_ctl_if.wspawn[pc][15]}] [get_ports {warp_ctl_if.wspawn[pc][14]}] [get_ports {warp_ctl_if.wspawn[pc][13]}] [get_ports {warp_ctl_if.wspawn[pc][12]}] [get_ports {warp_ctl_if.wspawn[pc][11]}] [get_ports {warp_ctl_if.wspawn[pc][10]}] [get_ports {warp_ctl_if.wspawn[pc][9]}] [get_ports {warp_ctl_if.wspawn[pc][8]}] [get_ports {warp_ctl_if.wspawn[pc][7]}] [get_ports {warp_ctl_if.wspawn[pc][6]}] [get_ports {warp_ctl_if.wspawn[pc][5]}] [get_ports {warp_ctl_if.wspawn[pc][4]}] [get_ports {warp_ctl_if.wspawn[pc][3]}] [get_ports {warp_ctl_if.wspawn[pc][2]}] [get_ports {warp_ctl_if.wspawn[pc][1]}] [get_ports {warp_ctl_if.wspawn[pc][0]}] [get_ports {warp_ctl_if.tmc[valid]}] [get_ports {warp_ctl_if.tmc[tmask][3]}] [get_ports {warp_ctl_if.tmc[tmask][2]}] [get_ports {warp_ctl_if.tmc[tmask][1]}] [get_ports {warp_ctl_if.tmc[tmask][0]}] [get_ports {warp_ctl_if.split[valid]}] [get_ports {warp_ctl_if.split[is_dvg]}] [get_ports {warp_ctl_if.split[then_tmask][3]}] [get_ports {warp_ctl_if.split[then_tmask][2]}] [get_ports {warp_ctl_if.split[then_tmask][1]}] [get_ports {warp_ctl_if.split[then_tmask][0]}] [get_ports {warp_ctl_if.split[else_tmask][3]}] [get_ports {warp_ctl_if.split[else_tmask][2]}] [get_ports {warp_ctl_if.split[else_tmask][1]}] [get_ports {warp_ctl_if.split[else_tmask][0]}] [get_ports {warp_ctl_if.split[next_pc][29]}] [get_ports {warp_ctl_if.split[next_pc][28]}] [get_ports {warp_ctl_if.split[next_pc][27]}] [get_ports {warp_ctl_if.split[next_pc][26]}] [get_ports {warp_ctl_if.split[next_pc][25]}] [get_ports {warp_ctl_if.split[next_pc][24]}] [get_ports {warp_ctl_if.split[next_pc][23]}] [get_ports {warp_ctl_if.split[next_pc][22]}] [get_ports {warp_ctl_if.split[next_pc][21]}] [get_ports {warp_ctl_if.split[next_pc][20]}] [get_ports {warp_ctl_if.split[next_pc][19]}] [get_ports {warp_ctl_if.split[next_pc][18]}] [get_ports {warp_ctl_if.split[next_pc][17]}] [get_ports {warp_ctl_if.split[next_pc][16]}] [get_ports {warp_ctl_if.split[next_pc][15]}] [get_ports {warp_ctl_if.split[next_pc][14]}] [get_ports {warp_ctl_if.split[next_pc][13]}] [get_ports {warp_ctl_if.split[next_pc][12]}] [get_ports {warp_ctl_if.split[next_pc][11]}] [get_ports {warp_ctl_if.split[next_pc][10]}] [get_ports {warp_ctl_if.split[next_pc][9]}] [get_ports {warp_ctl_if.split[next_pc][8]}] [get_ports {warp_ctl_if.split[next_pc][7]}] [get_ports {warp_ctl_if.split[next_pc][6]}] [get_ports {warp_ctl_if.split[next_pc][5]}] [get_ports {warp_ctl_if.split[next_pc][4]}] [get_ports {warp_ctl_if.split[next_pc][3]}] [get_ports {warp_ctl_if.split[next_pc][2]}] [get_ports {warp_ctl_if.split[next_pc][1]}] [get_ports {warp_ctl_if.split[next_pc][0]}] [get_ports {warp_ctl_if.sjoin[valid]}] [get_ports {warp_ctl_if.sjoin[stack_ptr][1]}] [get_ports {warp_ctl_if.sjoin[stack_ptr][0]}] [get_ports {warp_ctl_if.barrier[valid]}] [get_ports {warp_ctl_if.barrier[id][0]}] [get_ports {warp_ctl_if.barrier[is_global]}] [get_ports {warp_ctl_if.barrier[size_m1][1]}] [get_ports {warp_ctl_if.barrier[size_m1][0]}] [get_ports {warp_ctl_if.barrier[is_noop]}] [get_ports {warp_ctl_if.dvstack_wid[1]}] [get_ports {warp_ctl_if.dvstack_wid[0]}] [get_ports {branch_ctl_if[0].valid}] [get_ports {branch_ctl_if[0].wid[1]}] [get_ports {branch_ctl_if[0].wid[0]}] [get_ports {branch_ctl_if[0].taken}] [get_ports {branch_ctl_if[0].dest[29]}] [get_ports {branch_ctl_if[0].dest[28]}] [get_ports {branch_ctl_if[0].dest[27]}] [get_ports {branch_ctl_if[0].dest[26]}] [get_ports {branch_ctl_if[0].dest[25]}] [get_ports {branch_ctl_if[0].dest[24]}] [get_ports {branch_ctl_if[0].dest[23]}] [get_ports {branch_ctl_if[0].dest[22]}] [get_ports {branch_ctl_if[0].dest[21]}] [get_ports {branch_ctl_if[0].dest[20]}] [get_ports {branch_ctl_if[0].dest[19]}] [get_ports {branch_ctl_if[0].dest[18]}] [get_ports {branch_ctl_if[0].dest[17]}] [get_ports {branch_ctl_if[0].dest[16]}] [get_ports {branch_ctl_if[0].dest[15]}] [get_ports {branch_ctl_if[0].dest[14]}] [get_ports {branch_ctl_if[0].dest[13]}] [get_ports {branch_ctl_if[0].dest[12]}] [get_ports {branch_ctl_if[0].dest[11]}] [get_ports {branch_ctl_if[0].dest[10]}] [get_ports {branch_ctl_if[0].dest[9]}] [get_ports {branch_ctl_if[0].dest[8]}] [get_ports {branch_ctl_if[0].dest[7]}] [get_ports {branch_ctl_if[0].dest[6]}] [get_ports {branch_ctl_if[0].dest[5]}] [get_ports {branch_ctl_if[0].dest[4]}] [get_ports {branch_ctl_if[0].dest[3]}] [get_ports {branch_ctl_if[0].dest[2]}] [get_ports {branch_ctl_if[0].dest[1]}] [get_ports {branch_ctl_if[0].dest[0]}] [get_ports decode_sched_if.valid] [get_ports decode_sched_if.unlock] [get_ports {decode_sched_if.wid[1]}] [get_ports {decode_sched_if.wid[0]}] [get_ports {issue_sched_if[0].valid}] [get_ports {issue_sched_if[0].wis[1]}] [get_ports {issue_sched_if[0].wis[0]}] [get_ports {commit_sched_if.committed_warps[3]}] [get_ports {commit_sched_if.committed_warps[2]}] [get_ports {commit_sched_if.committed_warps[1]}] [get_ports {commit_sched_if.committed_warps[0]}] [get_ports schedule_if.ready] [get_ports {sched_csr_if.alm_empty_wid[1]}] [get_ports {sched_csr_if.alm_empty_wid[0]}] [get_ports {sched_csr_if.unlock_wid[1]}] [get_ports {sched_csr_if.unlock_wid[0]}] [get_ports sched_csr_if.unlock_warp]]  -to [list [get_ports {warp_ctl_if.dvstack_ptr[1]}] [get_ports {warp_ctl_if.dvstack_ptr[0]}] [get_ports schedule_if.valid] [get_ports {schedule_if.data[uuid][0]}] [get_ports {schedule_if.data[wid][1]}] [get_ports {schedule_if.data[wid][0]}] [get_ports {schedule_if.data[tmask][3]}] [get_ports {schedule_if.data[tmask][2]}] [get_ports {schedule_if.data[tmask][1]}] [get_ports {schedule_if.data[tmask][0]}] [get_ports {schedule_if.data[PC][29]}] [get_ports {schedule_if.data[PC][28]}] [get_ports {schedule_if.data[PC][27]}] [get_ports {schedule_if.data[PC][26]}] [get_ports {schedule_if.data[PC][25]}] [get_ports {schedule_if.data[PC][24]}] [get_ports {schedule_if.data[PC][23]}] [get_ports {schedule_if.data[PC][22]}] [get_ports {schedule_if.data[PC][21]}] [get_ports {schedule_if.data[PC][20]}] [get_ports {schedule_if.data[PC][19]}] [get_ports {schedule_if.data[PC][18]}] [get_ports {schedule_if.data[PC][17]}] [get_ports {schedule_if.data[PC][16]}] [get_ports {schedule_if.data[PC][15]}] [get_ports {schedule_if.data[PC][14]}] [get_ports {schedule_if.data[PC][13]}] [get_ports {schedule_if.data[PC][12]}] [get_ports {schedule_if.data[PC][11]}] [get_ports {schedule_if.data[PC][10]}] [get_ports {schedule_if.data[PC][9]}] [get_ports {schedule_if.data[PC][8]}] [get_ports {schedule_if.data[PC][7]}] [get_ports {schedule_if.data[PC][6]}] [get_ports {schedule_if.data[PC][5]}] [get_ports {schedule_if.data[PC][4]}] [get_ports {schedule_if.data[PC][3]}] [get_ports {schedule_if.data[PC][2]}] [get_ports {schedule_if.data[PC][1]}] [get_ports {schedule_if.data[PC][0]}] [get_ports {sched_csr_if.cycles[43]}] [get_ports {sched_csr_if.cycles[42]}] [get_ports {sched_csr_if.cycles[41]}] [get_ports {sched_csr_if.cycles[40]}] [get_ports {sched_csr_if.cycles[39]}] [get_ports {sched_csr_if.cycles[38]}] [get_ports {sched_csr_if.cycles[37]}] [get_ports {sched_csr_if.cycles[36]}] [get_ports {sched_csr_if.cycles[35]}] [get_ports {sched_csr_if.cycles[34]}] [get_ports {sched_csr_if.cycles[33]}] [get_ports {sched_csr_if.cycles[32]}] [get_ports {sched_csr_if.cycles[31]}] [get_ports {sched_csr_if.cycles[30]}] [get_ports {sched_csr_if.cycles[29]}] [get_ports {sched_csr_if.cycles[28]}] [get_ports {sched_csr_if.cycles[27]}] [get_ports {sched_csr_if.cycles[26]}] [get_ports {sched_csr_if.cycles[25]}] [get_ports {sched_csr_if.cycles[24]}] [get_ports {sched_csr_if.cycles[23]}] [get_ports {sched_csr_if.cycles[22]}] [get_ports {sched_csr_if.cycles[21]}] [get_ports {sched_csr_if.cycles[20]}] [get_ports {sched_csr_if.cycles[19]}] [get_ports {sched_csr_if.cycles[18]}] [get_ports {sched_csr_if.cycles[17]}] [get_ports {sched_csr_if.cycles[16]}] [get_ports {sched_csr_if.cycles[15]}] [get_ports {sched_csr_if.cycles[14]}] [get_ports {sched_csr_if.cycles[13]}] [get_ports {sched_csr_if.cycles[12]}] [get_ports {sched_csr_if.cycles[11]}] [get_ports {sched_csr_if.cycles[10]}] [get_ports {sched_csr_if.cycles[9]}] [get_ports {sched_csr_if.cycles[8]}] [get_ports {sched_csr_if.cycles[7]}] [get_ports {sched_csr_if.cycles[6]}] [get_ports {sched_csr_if.cycles[5]}] [get_ports {sched_csr_if.cycles[4]}] [get_ports {sched_csr_if.cycles[3]}] [get_ports {sched_csr_if.cycles[2]}] [get_ports {sched_csr_if.cycles[1]}] [get_ports {sched_csr_if.cycles[0]}] [get_ports {sched_csr_if.active_warps[3]}] [get_ports {sched_csr_if.active_warps[2]}] [get_ports {sched_csr_if.active_warps[1]}] [get_ports {sched_csr_if.active_warps[0]}] [get_ports {sched_csr_if.thread_masks[3][3]}] [get_ports {sched_csr_if.thread_masks[3][2]}] [get_ports {sched_csr_if.thread_masks[3][1]}] [get_ports {sched_csr_if.thread_masks[3][0]}] [get_ports {sched_csr_if.thread_masks[2][3]}] [get_ports {sched_csr_if.thread_masks[2][2]}] [get_ports {sched_csr_if.thread_masks[2][1]}] [get_ports {sched_csr_if.thread_masks[2][0]}] [get_ports {sched_csr_if.thread_masks[1][3]}] [get_ports {sched_csr_if.thread_masks[1][2]}] [get_ports {sched_csr_if.thread_masks[1][1]}] [get_ports {sched_csr_if.thread_masks[1][0]}] [get_ports {sched_csr_if.thread_masks[0][3]}] [get_ports {sched_csr_if.thread_masks[0][2]}] [get_ports {sched_csr_if.thread_masks[0][1]}] [get_ports {sched_csr_if.thread_masks[0][0]}] [get_ports sched_csr_if.alm_empty] [get_ports busy]]
group_path -name INREG  -from [list [get_ports clk] [get_ports reset] [get_ports {base_dcrs[startup_addr][31]}] [get_ports {base_dcrs[startup_addr][30]}] [get_ports {base_dcrs[startup_addr][29]}] [get_ports {base_dcrs[startup_addr][28]}] [get_ports {base_dcrs[startup_addr][27]}] [get_ports {base_dcrs[startup_addr][26]}] [get_ports {base_dcrs[startup_addr][25]}] [get_ports {base_dcrs[startup_addr][24]}] [get_ports {base_dcrs[startup_addr][23]}] [get_ports {base_dcrs[startup_addr][22]}] [get_ports {base_dcrs[startup_addr][21]}] [get_ports {base_dcrs[startup_addr][20]}] [get_ports {base_dcrs[startup_addr][19]}] [get_ports {base_dcrs[startup_addr][18]}] [get_ports {base_dcrs[startup_addr][17]}] [get_ports {base_dcrs[startup_addr][16]}] [get_ports {base_dcrs[startup_addr][15]}] [get_ports {base_dcrs[startup_addr][14]}] [get_ports {base_dcrs[startup_addr][13]}] [get_ports {base_dcrs[startup_addr][12]}] [get_ports {base_dcrs[startup_addr][11]}] [get_ports {base_dcrs[startup_addr][10]}] [get_ports {base_dcrs[startup_addr][9]}] [get_ports {base_dcrs[startup_addr][8]}] [get_ports {base_dcrs[startup_addr][7]}] [get_ports {base_dcrs[startup_addr][6]}] [get_ports {base_dcrs[startup_addr][5]}] [get_ports {base_dcrs[startup_addr][4]}] [get_ports {base_dcrs[startup_addr][3]}] [get_ports {base_dcrs[startup_addr][2]}] [get_ports {base_dcrs[startup_addr][1]}] [get_ports {base_dcrs[startup_addr][0]}] [get_ports {base_dcrs[startup_arg][31]}] [get_ports {base_dcrs[startup_arg][30]}] [get_ports {base_dcrs[startup_arg][29]}] [get_ports {base_dcrs[startup_arg][28]}] [get_ports {base_dcrs[startup_arg][27]}] [get_ports {base_dcrs[startup_arg][26]}] [get_ports {base_dcrs[startup_arg][25]}] [get_ports {base_dcrs[startup_arg][24]}] [get_ports {base_dcrs[startup_arg][23]}] [get_ports {base_dcrs[startup_arg][22]}] [get_ports {base_dcrs[startup_arg][21]}] [get_ports {base_dcrs[startup_arg][20]}] [get_ports {base_dcrs[startup_arg][19]}] [get_ports {base_dcrs[startup_arg][18]}] [get_ports {base_dcrs[startup_arg][17]}] [get_ports {base_dcrs[startup_arg][16]}] [get_ports {base_dcrs[startup_arg][15]}] [get_ports {base_dcrs[startup_arg][14]}] [get_ports {base_dcrs[startup_arg][13]}] [get_ports {base_dcrs[startup_arg][12]}] [get_ports {base_dcrs[startup_arg][11]}] [get_ports {base_dcrs[startup_arg][10]}] [get_ports {base_dcrs[startup_arg][9]}] [get_ports {base_dcrs[startup_arg][8]}] [get_ports {base_dcrs[startup_arg][7]}] [get_ports {base_dcrs[startup_arg][6]}] [get_ports {base_dcrs[startup_arg][5]}] [get_ports {base_dcrs[startup_arg][4]}] [get_ports {base_dcrs[startup_arg][3]}] [get_ports {base_dcrs[startup_arg][2]}] [get_ports {base_dcrs[startup_arg][1]}] [get_ports {base_dcrs[startup_arg][0]}] [get_ports {base_dcrs[mpm_class][7]}] [get_ports {base_dcrs[mpm_class][6]}] [get_ports {base_dcrs[mpm_class][5]}] [get_ports {base_dcrs[mpm_class][4]}] [get_ports {base_dcrs[mpm_class][3]}] [get_ports {base_dcrs[mpm_class][2]}] [get_ports {base_dcrs[mpm_class][1]}] [get_ports {base_dcrs[mpm_class][0]}] [get_ports warp_ctl_if.valid] [get_ports {warp_ctl_if.wid[1]}] [get_ports {warp_ctl_if.wid[0]}] [get_ports {warp_ctl_if.wspawn[valid]}] [get_ports {warp_ctl_if.wspawn[wmask][3]}] [get_ports {warp_ctl_if.wspawn[wmask][2]}] [get_ports {warp_ctl_if.wspawn[wmask][1]}] [get_ports {warp_ctl_if.wspawn[wmask][0]}] [get_ports {warp_ctl_if.wspawn[pc][29]}] [get_ports {warp_ctl_if.wspawn[pc][28]}] [get_ports {warp_ctl_if.wspawn[pc][27]}] [get_ports {warp_ctl_if.wspawn[pc][26]}] [get_ports {warp_ctl_if.wspawn[pc][25]}] [get_ports {warp_ctl_if.wspawn[pc][24]}] [get_ports {warp_ctl_if.wspawn[pc][23]}] [get_ports {warp_ctl_if.wspawn[pc][22]}] [get_ports {warp_ctl_if.wspawn[pc][21]}] [get_ports {warp_ctl_if.wspawn[pc][20]}] [get_ports {warp_ctl_if.wspawn[pc][19]}] [get_ports {warp_ctl_if.wspawn[pc][18]}] [get_ports {warp_ctl_if.wspawn[pc][17]}] [get_ports {warp_ctl_if.wspawn[pc][16]}] [get_ports {warp_ctl_if.wspawn[pc][15]}] [get_ports {warp_ctl_if.wspawn[pc][14]}] [get_ports {warp_ctl_if.wspawn[pc][13]}] [get_ports {warp_ctl_if.wspawn[pc][12]}] [get_ports {warp_ctl_if.wspawn[pc][11]}] [get_ports {warp_ctl_if.wspawn[pc][10]}] [get_ports {warp_ctl_if.wspawn[pc][9]}] [get_ports {warp_ctl_if.wspawn[pc][8]}] [get_ports {warp_ctl_if.wspawn[pc][7]}] [get_ports {warp_ctl_if.wspawn[pc][6]}] [get_ports {warp_ctl_if.wspawn[pc][5]}] [get_ports {warp_ctl_if.wspawn[pc][4]}] [get_ports {warp_ctl_if.wspawn[pc][3]}] [get_ports {warp_ctl_if.wspawn[pc][2]}] [get_ports {warp_ctl_if.wspawn[pc][1]}] [get_ports {warp_ctl_if.wspawn[pc][0]}] [get_ports {warp_ctl_if.tmc[valid]}] [get_ports {warp_ctl_if.tmc[tmask][3]}] [get_ports {warp_ctl_if.tmc[tmask][2]}] [get_ports {warp_ctl_if.tmc[tmask][1]}] [get_ports {warp_ctl_if.tmc[tmask][0]}] [get_ports {warp_ctl_if.split[valid]}] [get_ports {warp_ctl_if.split[is_dvg]}] [get_ports {warp_ctl_if.split[then_tmask][3]}] [get_ports {warp_ctl_if.split[then_tmask][2]}] [get_ports {warp_ctl_if.split[then_tmask][1]}] [get_ports {warp_ctl_if.split[then_tmask][0]}] [get_ports {warp_ctl_if.split[else_tmask][3]}] [get_ports {warp_ctl_if.split[else_tmask][2]}] [get_ports {warp_ctl_if.split[else_tmask][1]}] [get_ports {warp_ctl_if.split[else_tmask][0]}] [get_ports {warp_ctl_if.split[next_pc][29]}] [get_ports {warp_ctl_if.split[next_pc][28]}] [get_ports {warp_ctl_if.split[next_pc][27]}] [get_ports {warp_ctl_if.split[next_pc][26]}] [get_ports {warp_ctl_if.split[next_pc][25]}] [get_ports {warp_ctl_if.split[next_pc][24]}] [get_ports {warp_ctl_if.split[next_pc][23]}] [get_ports {warp_ctl_if.split[next_pc][22]}] [get_ports {warp_ctl_if.split[next_pc][21]}] [get_ports {warp_ctl_if.split[next_pc][20]}] [get_ports {warp_ctl_if.split[next_pc][19]}] [get_ports {warp_ctl_if.split[next_pc][18]}] [get_ports {warp_ctl_if.split[next_pc][17]}] [get_ports {warp_ctl_if.split[next_pc][16]}] [get_ports {warp_ctl_if.split[next_pc][15]}] [get_ports {warp_ctl_if.split[next_pc][14]}] [get_ports {warp_ctl_if.split[next_pc][13]}] [get_ports {warp_ctl_if.split[next_pc][12]}] [get_ports {warp_ctl_if.split[next_pc][11]}] [get_ports {warp_ctl_if.split[next_pc][10]}] [get_ports {warp_ctl_if.split[next_pc][9]}] [get_ports {warp_ctl_if.split[next_pc][8]}] [get_ports {warp_ctl_if.split[next_pc][7]}] [get_ports {warp_ctl_if.split[next_pc][6]}] [get_ports {warp_ctl_if.split[next_pc][5]}] [get_ports {warp_ctl_if.split[next_pc][4]}] [get_ports {warp_ctl_if.split[next_pc][3]}] [get_ports {warp_ctl_if.split[next_pc][2]}] [get_ports {warp_ctl_if.split[next_pc][1]}] [get_ports {warp_ctl_if.split[next_pc][0]}] [get_ports {warp_ctl_if.sjoin[valid]}] [get_ports {warp_ctl_if.sjoin[stack_ptr][1]}] [get_ports {warp_ctl_if.sjoin[stack_ptr][0]}] [get_ports {warp_ctl_if.barrier[valid]}] [get_ports {warp_ctl_if.barrier[id][0]}] [get_ports {warp_ctl_if.barrier[is_global]}] [get_ports {warp_ctl_if.barrier[size_m1][1]}] [get_ports {warp_ctl_if.barrier[size_m1][0]}] [get_ports {warp_ctl_if.barrier[is_noop]}] [get_ports {warp_ctl_if.dvstack_wid[1]}] [get_ports {warp_ctl_if.dvstack_wid[0]}] [get_ports {branch_ctl_if[0].valid}] [get_ports {branch_ctl_if[0].wid[1]}] [get_ports {branch_ctl_if[0].wid[0]}] [get_ports {branch_ctl_if[0].taken}] [get_ports {branch_ctl_if[0].dest[29]}] [get_ports {branch_ctl_if[0].dest[28]}] [get_ports {branch_ctl_if[0].dest[27]}] [get_ports {branch_ctl_if[0].dest[26]}] [get_ports {branch_ctl_if[0].dest[25]}] [get_ports {branch_ctl_if[0].dest[24]}] [get_ports {branch_ctl_if[0].dest[23]}] [get_ports {branch_ctl_if[0].dest[22]}] [get_ports {branch_ctl_if[0].dest[21]}] [get_ports {branch_ctl_if[0].dest[20]}] [get_ports {branch_ctl_if[0].dest[19]}] [get_ports {branch_ctl_if[0].dest[18]}] [get_ports {branch_ctl_if[0].dest[17]}] [get_ports {branch_ctl_if[0].dest[16]}] [get_ports {branch_ctl_if[0].dest[15]}] [get_ports {branch_ctl_if[0].dest[14]}] [get_ports {branch_ctl_if[0].dest[13]}] [get_ports {branch_ctl_if[0].dest[12]}] [get_ports {branch_ctl_if[0].dest[11]}] [get_ports {branch_ctl_if[0].dest[10]}] [get_ports {branch_ctl_if[0].dest[9]}] [get_ports {branch_ctl_if[0].dest[8]}] [get_ports {branch_ctl_if[0].dest[7]}] [get_ports {branch_ctl_if[0].dest[6]}] [get_ports {branch_ctl_if[0].dest[5]}] [get_ports {branch_ctl_if[0].dest[4]}] [get_ports {branch_ctl_if[0].dest[3]}] [get_ports {branch_ctl_if[0].dest[2]}] [get_ports {branch_ctl_if[0].dest[1]}] [get_ports {branch_ctl_if[0].dest[0]}] [get_ports decode_sched_if.valid] [get_ports decode_sched_if.unlock] [get_ports {decode_sched_if.wid[1]}] [get_ports {decode_sched_if.wid[0]}] [get_ports {issue_sched_if[0].valid}] [get_ports {issue_sched_if[0].wis[1]}] [get_ports {issue_sched_if[0].wis[0]}] [get_ports {commit_sched_if.committed_warps[3]}] [get_ports {commit_sched_if.committed_warps[2]}] [get_ports {commit_sched_if.committed_warps[1]}] [get_ports {commit_sched_if.committed_warps[0]}] [get_ports schedule_if.ready] [get_ports {sched_csr_if.alm_empty_wid[1]}] [get_ports {sched_csr_if.alm_empty_wid[0]}] [get_ports {sched_csr_if.unlock_wid[1]}] [get_ports {sched_csr_if.unlock_wid[0]}] [get_ports sched_csr_if.unlock_warp]]
group_path -name REGOUT  -to [list [get_ports {warp_ctl_if.dvstack_ptr[1]}] [get_ports {warp_ctl_if.dvstack_ptr[0]}] [get_ports schedule_if.valid] [get_ports {schedule_if.data[uuid][0]}] [get_ports {schedule_if.data[wid][1]}] [get_ports {schedule_if.data[wid][0]}] [get_ports {schedule_if.data[tmask][3]}] [get_ports {schedule_if.data[tmask][2]}] [get_ports {schedule_if.data[tmask][1]}] [get_ports {schedule_if.data[tmask][0]}] [get_ports {schedule_if.data[PC][29]}] [get_ports {schedule_if.data[PC][28]}] [get_ports {schedule_if.data[PC][27]}] [get_ports {schedule_if.data[PC][26]}] [get_ports {schedule_if.data[PC][25]}] [get_ports {schedule_if.data[PC][24]}] [get_ports {schedule_if.data[PC][23]}] [get_ports {schedule_if.data[PC][22]}] [get_ports {schedule_if.data[PC][21]}] [get_ports {schedule_if.data[PC][20]}] [get_ports {schedule_if.data[PC][19]}] [get_ports {schedule_if.data[PC][18]}] [get_ports {schedule_if.data[PC][17]}] [get_ports {schedule_if.data[PC][16]}] [get_ports {schedule_if.data[PC][15]}] [get_ports {schedule_if.data[PC][14]}] [get_ports {schedule_if.data[PC][13]}] [get_ports {schedule_if.data[PC][12]}] [get_ports {schedule_if.data[PC][11]}] [get_ports {schedule_if.data[PC][10]}] [get_ports {schedule_if.data[PC][9]}] [get_ports {schedule_if.data[PC][8]}] [get_ports {schedule_if.data[PC][7]}] [get_ports {schedule_if.data[PC][6]}] [get_ports {schedule_if.data[PC][5]}] [get_ports {schedule_if.data[PC][4]}] [get_ports {schedule_if.data[PC][3]}] [get_ports {schedule_if.data[PC][2]}] [get_ports {schedule_if.data[PC][1]}] [get_ports {schedule_if.data[PC][0]}] [get_ports {sched_csr_if.cycles[43]}] [get_ports {sched_csr_if.cycles[42]}] [get_ports {sched_csr_if.cycles[41]}] [get_ports {sched_csr_if.cycles[40]}] [get_ports {sched_csr_if.cycles[39]}] [get_ports {sched_csr_if.cycles[38]}] [get_ports {sched_csr_if.cycles[37]}] [get_ports {sched_csr_if.cycles[36]}] [get_ports {sched_csr_if.cycles[35]}] [get_ports {sched_csr_if.cycles[34]}] [get_ports {sched_csr_if.cycles[33]}] [get_ports {sched_csr_if.cycles[32]}] [get_ports {sched_csr_if.cycles[31]}] [get_ports {sched_csr_if.cycles[30]}] [get_ports {sched_csr_if.cycles[29]}] [get_ports {sched_csr_if.cycles[28]}] [get_ports {sched_csr_if.cycles[27]}] [get_ports {sched_csr_if.cycles[26]}] [get_ports {sched_csr_if.cycles[25]}] [get_ports {sched_csr_if.cycles[24]}] [get_ports {sched_csr_if.cycles[23]}] [get_ports {sched_csr_if.cycles[22]}] [get_ports {sched_csr_if.cycles[21]}] [get_ports {sched_csr_if.cycles[20]}] [get_ports {sched_csr_if.cycles[19]}] [get_ports {sched_csr_if.cycles[18]}] [get_ports {sched_csr_if.cycles[17]}] [get_ports {sched_csr_if.cycles[16]}] [get_ports {sched_csr_if.cycles[15]}] [get_ports {sched_csr_if.cycles[14]}] [get_ports {sched_csr_if.cycles[13]}] [get_ports {sched_csr_if.cycles[12]}] [get_ports {sched_csr_if.cycles[11]}] [get_ports {sched_csr_if.cycles[10]}] [get_ports {sched_csr_if.cycles[9]}] [get_ports {sched_csr_if.cycles[8]}] [get_ports {sched_csr_if.cycles[7]}] [get_ports {sched_csr_if.cycles[6]}] [get_ports {sched_csr_if.cycles[5]}] [get_ports {sched_csr_if.cycles[4]}] [get_ports {sched_csr_if.cycles[3]}] [get_ports {sched_csr_if.cycles[2]}] [get_ports {sched_csr_if.cycles[1]}] [get_ports {sched_csr_if.cycles[0]}] [get_ports {sched_csr_if.active_warps[3]}] [get_ports {sched_csr_if.active_warps[2]}] [get_ports {sched_csr_if.active_warps[1]}] [get_ports {sched_csr_if.active_warps[0]}] [get_ports {sched_csr_if.thread_masks[3][3]}] [get_ports {sched_csr_if.thread_masks[3][2]}] [get_ports {sched_csr_if.thread_masks[3][1]}] [get_ports {sched_csr_if.thread_masks[3][0]}] [get_ports {sched_csr_if.thread_masks[2][3]}] [get_ports {sched_csr_if.thread_masks[2][2]}] [get_ports {sched_csr_if.thread_masks[2][1]}] [get_ports {sched_csr_if.thread_masks[2][0]}] [get_ports {sched_csr_if.thread_masks[1][3]}] [get_ports {sched_csr_if.thread_masks[1][2]}] [get_ports {sched_csr_if.thread_masks[1][1]}] [get_ports {sched_csr_if.thread_masks[1][0]}] [get_ports {sched_csr_if.thread_masks[0][3]}] [get_ports {sched_csr_if.thread_masks[0][2]}] [get_ports {sched_csr_if.thread_masks[0][1]}] [get_ports {sched_csr_if.thread_masks[0][0]}] [get_ports sched_csr_if.alm_empty] [get_ports busy]]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][31]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][30]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][29]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][28]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][27]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][26]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][25]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][24]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][23]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][22]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][21]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][20]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][19]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][18]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][17]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][16]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][15]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][14]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][13]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][12]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][11]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][10]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][9]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][8]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][7]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][6]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][5]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][4]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][3]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][2]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][1]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_addr][0]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][31]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][30]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][29]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][28]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][27]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][26]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][25]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][24]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][23]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][22]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][21]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][20]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][19]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][18]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][17]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][16]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][15]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][14]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][13]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][12]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][11]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][10]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][9]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][8]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][7]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][6]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][5]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][4]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][3]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][2]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][1]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[startup_arg][0]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[mpm_class][7]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[mpm_class][6]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[mpm_class][5]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[mpm_class][4]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[mpm_class][3]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[mpm_class][2]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[mpm_class][1]}]
set_input_delay -clock CLK  1.2  [get_ports {base_dcrs[mpm_class][0]}]
set_input_delay -clock CLK  1.2  [get_ports warp_ctl_if.valid]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wid[1]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wid[0]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[valid]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[wmask][3]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[wmask][2]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[wmask][1]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[wmask][0]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][29]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][28]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][27]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][26]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][25]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][24]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][23]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][22]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][21]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][20]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][19]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][18]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][17]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][16]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][15]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][14]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][13]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][12]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][11]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][10]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][9]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][8]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][7]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][6]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][5]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][4]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][3]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][2]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][1]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.wspawn[pc][0]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.tmc[valid]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.tmc[tmask][3]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.tmc[tmask][2]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.tmc[tmask][1]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.tmc[tmask][0]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[valid]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[is_dvg]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[then_tmask][3]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[then_tmask][2]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[then_tmask][1]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[then_tmask][0]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[else_tmask][3]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[else_tmask][2]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[else_tmask][1]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[else_tmask][0]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][29]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][28]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][27]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][26]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][25]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][24]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][23]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][22]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][21]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][20]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][19]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][18]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][17]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][16]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][15]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][14]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][13]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][12]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][11]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][10]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][9]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][8]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][7]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][6]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][5]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][4]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][3]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][2]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][1]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.split[next_pc][0]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.sjoin[valid]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.sjoin[stack_ptr][1]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.sjoin[stack_ptr][0]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.barrier[valid]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.barrier[id][0]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.barrier[is_global]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.barrier[size_m1][1]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.barrier[size_m1][0]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.barrier[is_noop]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.dvstack_wid[1]}]
set_input_delay -clock CLK  1.2  [get_ports {warp_ctl_if.dvstack_wid[0]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].valid}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].wid[1]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].wid[0]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].taken}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[29]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[28]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[27]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[26]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[25]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[24]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[23]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[22]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[21]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[20]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[19]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[18]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[17]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[16]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[15]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[14]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[13]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[12]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[11]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[10]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[9]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[8]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[7]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[6]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[5]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[4]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[3]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[2]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[1]}]
set_input_delay -clock CLK  1.2  [get_ports {branch_ctl_if[0].dest[0]}]
set_input_delay -clock CLK  1.2  [get_ports decode_sched_if.valid]
set_input_delay -clock CLK  1.2  [get_ports decode_sched_if.unlock]
set_input_delay -clock CLK  1.2  [get_ports {decode_sched_if.wid[1]}]
set_input_delay -clock CLK  1.2  [get_ports {decode_sched_if.wid[0]}]
set_input_delay -clock CLK  1.2  [get_ports {issue_sched_if[0].valid}]
set_input_delay -clock CLK  1.2  [get_ports {issue_sched_if[0].wis[1]}]
set_input_delay -clock CLK  1.2  [get_ports {issue_sched_if[0].wis[0]}]
set_input_delay -clock CLK  1.2  [get_ports {commit_sched_if.committed_warps[3]}]
set_input_delay -clock CLK  1.2  [get_ports {commit_sched_if.committed_warps[2]}]
set_input_delay -clock CLK  1.2  [get_ports {commit_sched_if.committed_warps[1]}]
set_input_delay -clock CLK  1.2  [get_ports {commit_sched_if.committed_warps[0]}]
set_input_delay -clock CLK  1.2  [get_ports schedule_if.ready]
set_input_delay -clock CLK  1.2  [get_ports {sched_csr_if.alm_empty_wid[1]}]
set_input_delay -clock CLK  1.2  [get_ports {sched_csr_if.alm_empty_wid[0]}]
set_input_delay -clock CLK  1.2  [get_ports {sched_csr_if.unlock_wid[1]}]
set_input_delay -clock CLK  1.2  [get_ports {sched_csr_if.unlock_wid[0]}]
set_input_delay -clock CLK  1.2  [get_ports sched_csr_if.unlock_warp]
set_output_delay -clock CLK  1.2  [get_ports {warp_ctl_if.dvstack_ptr[1]}]
set_output_delay -clock CLK  1.2  [get_ports {warp_ctl_if.dvstack_ptr[0]}]
set_output_delay -clock CLK  1.2  [get_ports schedule_if.valid]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[uuid][0]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[wid][1]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[wid][0]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[tmask][3]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[tmask][2]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[tmask][1]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[tmask][0]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][29]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][28]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][27]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][26]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][25]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][24]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][23]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][22]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][21]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][20]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][19]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][18]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][17]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][16]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][15]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][14]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][13]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][12]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][11]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][10]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][9]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][8]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][7]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][6]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][5]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][4]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][3]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][2]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][1]}]
set_output_delay -clock CLK  1.2  [get_ports {schedule_if.data[PC][0]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[43]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[42]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[41]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[40]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[39]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[38]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[37]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[36]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[35]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[34]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[33]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[32]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[31]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[30]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[29]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[28]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[27]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[26]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[25]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[24]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[23]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[22]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[21]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[20]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[19]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[18]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[17]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[16]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[15]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[14]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[13]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[12]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[11]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[10]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[9]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[8]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[7]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[6]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[5]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[4]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[3]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[2]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[1]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.cycles[0]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.active_warps[3]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.active_warps[2]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.active_warps[1]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.active_warps[0]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[3][3]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[3][2]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[3][1]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[3][0]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[2][3]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[2][2]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[2][1]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[2][0]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[1][3]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[1][2]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[1][1]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[1][0]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[0][3]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[0][2]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[0][1]}]
set_output_delay -clock CLK  1.2  [get_ports {sched_csr_if.thread_masks[0][0]}]
set_output_delay -clock CLK  1.2  [get_ports sched_csr_if.alm_empty]
set_output_delay -clock CLK  1.2  [get_ports busy]
